name: Rclone Synchronizing
on:
  gollum
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Inject Rclone config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
    - name: Rclone Synchronizing file
      run: |
        rclone copy downloads `cat DEST`
